--- 
repos:
- 
  hooks: 
    - 
      entry: "bash -c 'pytest'"
      id: pytest-check
      language: system
      name: pytest-check
  repo: local
-
  hooks: 
    - 
      id: black
      language_version: python3
  repo: https://github.com/ambv/black
  rev: stable

  
