--- 
repos:
-
  hooks: 
    - 
      id: black
      language_version: python3
  repo: https://github.com/ambv/black
  rev: 20.8b1
- 
  hooks: 
    - 
      entry: "bash -c 'pytest'"
      id: pytest-check
      language: system
      name: pytest-check
      pass_filenames: false
      always_run: true
  repo: local


  
